#!/bin/bash
set -ex

# ============================================================
# SDL2 build for tg5040 NDS (drastic) with compiled-in hooks
#
# Same hook patches as tg5050 but WITHOUT DRM/GBM:
# - tg5040 renders via /dev/fb0 + PowerVR EGL (not DRM)
# - No -DADVDRASTIC_DRM flag
# - Dummy driver reads resolution from framebuffer ioctl
# - eglSwapInterval(1) for fbdev vsync (no DRM page flips)
# ============================================================

# ============================================================
# Step 1: Set up toolchain environment
# ============================================================
source ~/.bashrc

# Paths default to the cwd layout used by `make build` (cwd =
# workspace/<platform>/other/sdl2-drastic); workspace/all/prebuilts/sdl2-drastic.sh
# overrides them to build in its own work dir.
OUT_DIR="${OUT_DIR:-$(pwd)/output}"
EXTRA_PREFIX="${EXTRA_PREFIX:-$(pwd)/extra-deps}"
SDL_SRC_DIR="${SDL_SRC_DIR:-$(pwd)/SDL_drastic}"
EXTRA_CFLAGS="${EXTRA_CFLAGS:-}"  # appended to CFLAGS (e.g. -ffile-prefix-map)

# Pinned header-only deps (json-c-0.15 branch tip == tag json-c-0.15-20200726)
JSONC_REPO=https://github.com/json-c/json-c.git
JSONC_COMMIT=9021cdcdd01fc9dbcbe1f06391848c2ac915212f

# Shallow-fetch one exact commit of a git repo into an empty directory
fetch_commit() {  # <repo> <commit> <dir>
    rm -rf "$3" && mkdir -p "$3"
    git -C "$3" init -q
    git -C "$3" fetch -q --depth 1 "$1" "$2"
    git -C "$3" checkout -q FETCH_HEAD
    [ "$(git -C "$3" rev-parse HEAD)" = "$2" ]
}
DEPS_TMP="$(mktemp -d)"

# ============================================================
# Step 2: Install extra-deps headers (json-c only)
# tg5040 uses fbdev/PowerVR — no DRM/GBM headers needed.
# EGL/GLES headers are already in the sysroot.
# ============================================================
if [ ! -f "$EXTRA_PREFIX/.deps_installed" ]; then
    mkdir -p "$EXTRA_PREFIX/include" "$EXTRA_PREFIX/lib"

    # json-c headers (needed by hook code's jsonlayout.c)
    fetch_commit "$JSONC_REPO" "$JSONC_COMMIT" "$DEPS_TMP/json-c"
    mkdir -p "$EXTRA_PREFIX/include/json-c"
    cp "$DEPS_TMP"/json-c/*.h "$EXTRA_PREFIX/include/json-c/"

    # json_config.h stub (normally generated by cmake)
    cat > "$EXTRA_PREFIX/include/json-c/json_config.h" << 'CONFEOF'
#ifndef _json_config_h_
#define _json_config_h_
#define JSON_C_HAVE_INTTYPES_H 1
#define JSON_C_HAVE_STDINT_H 1
#endif
CONFEOF

    # SDL2_ttf and SDL2_image headers (needed by hook code in drastic_video.h)
    cp ${SYSROOT}/usr/include/SDL2/SDL_ttf.h "$EXTRA_PREFIX/include/"
    cp ${SYSROOT}/usr/include/SDL2/SDL_image.h "$EXTRA_PREFIX/include/"

    # json-c stub library (symbols resolved on device)
    cat > "$DEPS_TMP/json_stub.c" << 'STUBEOF'
void json_object_new_int(void){} void json_object_put(void){} void json_object_to_file_ext(void){}
void json_object_from_file(void){} void json_object_object_add(void){} void json_object_get_string(void){}
void json_object_get_int(void){} void json_object_object_get_ex(void){} void json_object_new_string(void){}
void json_object_new_object(void){} void json_object_new_array(void){} void json_object_array_add(void){}
void json_object_array_length(void){} void json_object_array_get_idx(void){}
void json_object_object_get(void){} void json_object_get_type(void){}
STUBEOF
    ${CC} -shared -Wl,-soname,libjson-c.so.4 -o "$EXTRA_PREFIX/lib/libjson-c.so" "$DEPS_TMP/json_stub.c"

    rm -rf "$DEPS_TMP"
    touch "$EXTRA_PREFIX/.deps_installed"
    echo "=== Extra deps installed ==="
fi

# ============================================================
# Step 3: SDL_drastic source must be pre-cloned and patched
# Run 'make other/sdl2-drastic/SDL_drastic' from workspace/tg5040
# ============================================================
if [ ! -d "$SDL_SRC_DIR" ]; then
    echo "ERROR: SDL_drastic source not found. Run from workspace/tg5040:"
    echo "  make other/sdl2-drastic/SDL_drastic"
    exit 1
fi

cd "$SDL_SRC_DIR"

# ============================================================
# Step 4: Generate configure
# ============================================================
if [ ! -f configure ]; then
    ./autogen.sh
fi

# Clean previous build (force rebuild when CFLAGS change)
[ -f Makefile ] && make clean || true

# ============================================================
# Step 7: Configure — dummy driver + OpenGL ES (no KMSDRM)
# Note: Do NOT include sysroot SDL2 headers (version mismatch).
# The hook code's SDL2 includes resolve from the source tree.
# No -DADVDRASTIC_DRM: tg5040 uses /dev/fb0, not DRM.
# ============================================================
export PKG_CONFIG_PATH="${SYSROOT}/usr/lib/pkgconfig"
export PKG_CONFIG_SYSROOT_DIR=""

./configure \
    --host=${CROSS_TRIPLE} \
    --prefix=/usr \
    --enable-shared \
    --disable-static \
    --disable-rpath \
    --disable-arts \
    --disable-esd \
    --disable-dbus \
    --disable-pulseaudio \
    --disable-video-vivante \
    --disable-video-cocoa \
    --disable-video-metal \
    --enable-video-dummy \
    --disable-video-offscreen \
    --disable-video-x11 \
    --disable-video-wayland \
    --disable-video-kmsdrm \
    --disable-ime \
    --disable-ibus \
    --disable-fcitx \
    --disable-joystick-mfi \
    --disable-directx \
    --disable-xinput \
    --disable-wasapi \
    --disable-hidapi-joystick \
    --disable-hidapi-libusb \
    --disable-joystick-virtual \
    --disable-render-d3d \
    --disable-hidapi \
    --enable-video-opengles \
    --enable-video-opengles1 \
    --enable-video-opengles2 \
    --enable-alsa \
    --disable-libudev \
    CFLAGS="-O2 -Wno-error -DDEVICE_TRIMUI -I${EXTRA_PREFIX}/include ${EXTRA_CFLAGS}" \
    CPPFLAGS="-I${EXTRA_PREFIX}/include" \
    LDFLAGS="-L${EXTRA_PREFIX}/lib -L${SYSROOT}/usr/lib"

# Suppress -Werror flags (hook code has many harmless warnings)
sed -i 's/-Werror=declaration-after-statement/-Wno-error/g' Makefile

# ============================================================
# Step 8: Build — add hook link deps via EXTRA_LDFLAGS
# No -ldrm/-lgbm: tg5040 uses fbdev, not DRM/GBM.
# ============================================================
make -j$(nproc) \
    EXTRA_LDFLAGS="-L${EXTRA_PREFIX}/lib -L${SYSROOT}/usr/lib -lSDL2_image -lSDL2_ttf -ljson-c -lpthread -lEGL -lGLESv2 -lm -ldl"

# ============================================================
# Step 9: Output
# ============================================================
mkdir -p "$OUT_DIR"
cp build/.libs/libSDL2-2.0.so.0 "$OUT_DIR/"
echo "=== Build complete ==="
ls -la "$OUT_DIR/libSDL2-2.0.so.0"
file "$OUT_DIR/libSDL2-2.0.so.0"
strings "$OUT_DIR/libSDL2-2.0.so.0" | grep -i "FB display\|dummy\|DraStic"
