#!/bin/bash
set -ex

# Paths default to the cwd layout used by `make build` (cwd =
# workspace/<platform>/other/sdl2-drastic); workspace/all/prebuilts/sdl2-drastic.sh
# overrides them to build in its own work dir.
OUT_DIR="${OUT_DIR:-$(pwd)/output}"
EXTRA_PREFIX="${EXTRA_PREFIX:-$(pwd)/extra-deps}"
SDL_SRC_DIR="${SDL_SRC_DIR:-$(pwd)/SDL_drastic}"
EXTRA_CFLAGS="${EXTRA_CFLAGS:-}"  # appended to CFLAGS (e.g. -ffile-prefix-map)

# Pinned header-only deps
JSONC_REPO=https://github.com/json-c/json-c.git
JSONC_COMMIT=9021cdcdd01fc9dbcbe1f06391848c2ac915212f   # json-c-0.15-20200726
EGL_REGISTRY_REPO=https://github.com/KhronosGroup/EGL-Registry.git
EGL_REGISTRY_COMMIT=db3425b8246136faccb5e2782b5694960bd6edf1   # 2026-03-19
LIBDRM_REPO=https://gitlab.freedesktop.org/mesa/drm.git
LIBDRM_COMMIT=b97cbde15c5c3abfe44d78e8f57139e50f612fec
GBM_H_URL=https://gitlab.freedesktop.org/mesa/mesa/-/raw/0b2fa0445c2cdf6ab5e3a00214954670f0e0d2af/src/gbm/main/gbm.h
GBM_H_SHA256=95f3b4a6ee5175c7cc5d47368d4efb100063fe49e5a6f5b19030ac2ceed73b81

# Shallow-fetch one exact commit of a git repo into an empty directory
fetch_commit() {  # <repo> <commit> <dir>
    rm -rf "$3" && mkdir -p "$3"
    git -C "$3" init -q
    git -C "$3" fetch -q --depth 1 "$1" "$2"
    git -C "$3" checkout -q FETCH_HEAD
    [ "$(git -C "$3" rev-parse HEAD)" = "$2" ]
}
DEPS_TMP="$(mktemp -d)"

# ============================================================
# Step 1: Install missing headers and create pkg-config files
# ============================================================
if [ ! -d "$EXTRA_PREFIX/include/EGL" ]; then
    mkdir -p "$EXTRA_PREFIX/include" "$EXTRA_PREFIX/lib" "$EXTRA_PREFIX/lib/pkgconfig"

    # EGL/KHR headers (standard Khronos headers)
    fetch_commit "$EGL_REGISTRY_REPO" "$EGL_REGISTRY_COMMIT" "$DEPS_TMP/egl-registry"
    cp -r "$DEPS_TMP"/egl-registry/api/EGL "$EXTRA_PREFIX/include/"
    cp -r "$DEPS_TMP"/egl-registry/api/KHR "$EXTRA_PREFIX/include/"

    # GBM header
    wget -qO "$EXTRA_PREFIX/include/gbm.h" "$GBM_H_URL"
    echo "$GBM_H_SHA256  $EXTRA_PREFIX/include/gbm.h" | sha256sum -c -

    # libdrm headers
    fetch_commit "$LIBDRM_REPO" "$LIBDRM_COMMIT" "$DEPS_TMP/libdrm"
    mkdir -p "$EXTRA_PREFIX/include/libdrm"
    cp "$DEPS_TMP"/libdrm/include/drm/*.h "$EXTRA_PREFIX/include/libdrm/"
    cp "$DEPS_TMP"/libdrm/include/drm/*.h "$EXTRA_PREFIX/include/"
    cp "$DEPS_TMP"/libdrm/xf86drm.h "$DEPS_TMP"/libdrm/xf86drmMode.h "$EXTRA_PREFIX/include/"

    # json-c headers
    fetch_commit "$JSONC_REPO" "$JSONC_COMMIT" "$DEPS_TMP/json-c"
    mkdir -p "$EXTRA_PREFIX/include/json-c"
    cp "$DEPS_TMP"/json-c/*.h "$EXTRA_PREFIX/include/json-c/"

    # json_config.h stub (normally generated by cmake; same as the tg5040 script)
    cat > "$EXTRA_PREFIX/include/json-c/json_config.h" << 'CONFEOF'
#ifndef _json_config_h_
#define _json_config_h_
#define JSON_C_HAVE_INTTYPES_H 1
#define JSON_C_HAVE_STDINT_H 1
#endif
CONFEOF

    # SDL2_ttf and SDL2_image headers (needed by hook code in drastic_video.h)
    # Copy from sysroot — these are stable headers across SDL2 minor versions
    cp ${SYSROOT}/usr/include/SDL2/SDL_ttf.h "$EXTRA_PREFIX/include/"
    cp ${SYSROOT}/usr/include/SDL2/SDL_image.h "$EXTRA_PREFIX/include/"

    # EGL and GBM are exported by libmali on device. Point -lEGL/-lgbm straight at
    # it: an empty stub that merely depends on libmali does not satisfy
    # --no-undefined (binutils no longer resolves through indirect DSOs), and the
    # resulting NEEDED entry is libmali.so.0 either way.
    ln -sf "${SYSROOT}/usr/lib/libmali.so.0" "$EXTRA_PREFIX/lib/libEGL.so"
    ln -sf "${SYSROOT}/usr/lib/libmali.so.0" "$EXTRA_PREFIX/lib/libgbm.so"

    # json-c stub
    cat > "$DEPS_TMP/json_stub.c" << 'STUBEOF'
void json_object_new_int(void){} void json_object_put(void){} void json_object_to_file_ext(void){}
void json_object_from_file(void){} void json_object_object_add(void){} void json_object_get_string(void){}
void json_object_get_int(void){} void json_object_object_get_ex(void){} void json_object_new_string(void){}
void json_object_new_object(void){} void json_object_new_array(void){} void json_object_array_add(void){}
void json_object_array_length(void){} void json_object_array_get_idx(void){}
void json_object_object_get(void){} void json_object_get_type(void){}
STUBEOF
    ${CC} -shared -o "$EXTRA_PREFIX/lib/libjson-c.so" "$DEPS_TMP/json_stub.c"

    # pkg-config for libdrm (so configure detects KMSDRM)
    cat > "$EXTRA_PREFIX/lib/pkgconfig/libdrm.pc" << EOF
prefix=${EXTRA_PREFIX}
libdir=${SYSROOT}/usr/lib
includedir=${EXTRA_PREFIX}/include

Name: libdrm
Description: Direct Rendering Manager library
Version: 2.4.114
Libs: -L\${libdir} -ldrm
Cflags: -I\${includedir} -I\${includedir}/libdrm
EOF

    # pkg-config for gbm
    cat > "$EXTRA_PREFIX/lib/pkgconfig/gbm.pc" << EOF
prefix=${EXTRA_PREFIX}
libdir=${EXTRA_PREFIX}/lib
includedir=${EXTRA_PREFIX}/include

Name: gbm
Description: Generic Buffer Management
Version: 23.0.0
Libs: -L\${libdir} -lgbm
Cflags: -I\${includedir}
EOF

    # pkg-config for egl
    cat > "$EXTRA_PREFIX/lib/pkgconfig/egl.pc" << EOF
prefix=${EXTRA_PREFIX}
libdir=${EXTRA_PREFIX}/lib
includedir=${EXTRA_PREFIX}/include

Name: egl
Description: EGL library
Version: 1.5
Libs: -L\${libdir} -lEGL
Cflags: -I\${includedir}
EOF

    rm -rf "$DEPS_TMP"
    echo "=== Extra deps installed ==="
fi

# ============================================================
# Step 2: SDL_drastic source must be pre-cloned and patched
# Run 'make other/sdl2-drastic/SDL_drastic' from workspace/tg5050
# ============================================================
if [ ! -d "$SDL_SRC_DIR" ]; then
    echo "ERROR: SDL_drastic source not found. Run from workspace/tg5050:"
    echo "  make other/sdl2-drastic/SDL_drastic"
    exit 1
fi

cd "$SDL_SRC_DIR"

# ============================================================
# Step 3: Generate configure
# ============================================================
if [ ! -f configure ]; then
    ./autogen.sh
fi

# Clean previous build (force rebuild when CFLAGS change)
[ -f Makefile ] && make clean || true
rm -f .configured

# Fix broken .la files in sysroot (hardcoded paths from Trimui build env)
BROKEN_PREFIX="/home2/trimuidev/tg5050/tina_1.0.0/out/a523/gb1/buildroot/buildroot/host/bin/../aarch64-buildroot-linux-gnu/sysroot"
for la in ${SYSROOT}/usr/lib/*.la; do
    if grep -q "$BROKEN_PREFIX" "$la" 2>/dev/null; then
        sed -i "s|$BROKEN_PREFIX|$SYSROOT|g" "$la"
    fi
done

# ============================================================
# Step 5: Configure — KMSDRM + OpenGL ES
# Note: Do NOT include sysroot SDL2 headers (version mismatch).
# The hook code's SDL2 includes resolve from the source tree.
# ============================================================
export PKG_CONFIG_PATH="${EXTRA_PREFIX}/lib/pkgconfig:${SYSROOT}/usr/lib/pkgconfig"
export PKG_CONFIG_SYSROOT_DIR=""

./configure \
    --host=${CROSS_TRIPLE} \
    --prefix=/usr \
    --enable-shared \
    --disable-static \
    --disable-rpath \
    --disable-arts \
    --disable-esd \
    --disable-dbus \
    --disable-pulseaudio \
    --disable-video-vivante \
    --disable-video-cocoa \
    --disable-video-metal \
    --enable-video-dummy \
    --disable-video-offscreen \
    --disable-video-x11 \
    --disable-video-wayland \
    --disable-ime \
    --disable-ibus \
    --disable-fcitx \
    --disable-joystick-mfi \
    --disable-directx \
    --disable-xinput \
    --disable-wasapi \
    --disable-hidapi-joystick \
    --disable-hidapi-libusb \
    --disable-joystick-virtual \
    --disable-render-d3d \
    --disable-hidapi \
    --enable-video-kmsdrm \
    --enable-video-opengles \
    --enable-video-opengles1 \
    --enable-video-opengles2 \
    --enable-alsa \
    --enable-libudev \
    CFLAGS="-O2 -Wno-error -DDEVICE_TRIMUI -DADVDRASTIC_DRM -I${EXTRA_PREFIX}/include ${EXTRA_CFLAGS}" \
    CPPFLAGS="-I${EXTRA_PREFIX}/include" \
    LDFLAGS="-L${EXTRA_PREFIX}/lib -L${SYSROOT}/usr/lib"

# Verify KMSDRM was detected
if ! grep -q "SDL_VIDEO_DRIVER_KMSDRM" include/SDL_config.h; then
    echo "ERROR: KMSDRM video driver was not enabled!"
    exit 1
fi
echo "=== KMSDRM detected ==="

# Suppress -Werror flags (hook code has many harmless warnings)
sed -i 's/-Werror=declaration-after-statement/-Wno-error/g' Makefile

# ============================================================
# Step 6: Build — add hook link deps via EXTRA_LDFLAGS
# ============================================================
make -j$(nproc) \
    EXTRA_LDFLAGS="-L${EXTRA_PREFIX}/lib -L${SYSROOT}/usr/lib -Wl,-rpath-link,${SYSROOT}/usr/lib -lSDL2_image -lSDL2_ttf -ljson-c -lpthread -lEGL -lGLESv2 -ldrm -lgbm"

# ============================================================
# Step 7: Output
# ============================================================
mkdir -p "$OUT_DIR"
cp build/.libs/libSDL2-2.0.so.0 "$OUT_DIR/"
echo "=== Build complete (ADVDRASTIC_DRM enabled) ==="
ls -la "$OUT_DIR/libSDL2-2.0.so.0"
file "$OUT_DIR/libSDL2-2.0.so.0"
strings "$OUT_DIR/libSDL2-2.0.so.0" | grep -i "drm_init\|gbm_create\|Cannot create gbm"
